### ISSUE TITLE
TNS Names support

### ISSUE THREAD

**Issue by 4223** [tschf/atom-build-oracle#27]
Would be nice if there were an option to use an existing tnsnames.ora file

**Comment by tschf** [comment]
Once this change is published (1.5.0), you can use your TNS name through a new config option `connectString`. Goes without saying, you would need your `TNS_ADMIN` environment variable set so `sqlplus` knows where to look for your `tnsnames.ora`.

``` json
[
    {
        "targetName" : "hr",
        "connectString" : "hr/hr@XE1"
    }
]
```

You still need to specify a password in the connect string - it will just hang otherwise waiting for password input, with the build output not allowing you to enter anything.
